GET http://localhost:8000/api/siswa

###
GET http://localhost:8000/api/siswa/2

###
POST http://localhost:8000/api/siswa
Content-Type: application/json

{
    "name": "Tia Selpiani",
    "birth_place": "Jakarta",
    "birth_date": "28 September 1985",
    "phone": "081222299964",
    "email": "bundahijaz@semangka.com"
}

###
PUT http://localhost:8000/api/siswa/2
Content-Type: application/json

{
    "name": "Bunda Hijjaz",
    "birth_place": "Jakarta",
    "birth_date": "28 September 1985",
    "phone": "081222299964",
    "email": "bundahijaz@semangka.com"
}

###
DELETE http://localhost:8000/api/siswa/1