GET http://localhost:8000/api/user

###
GET http://localhost:8000/api/user/2

###
POST http://localhost:8000/api/user
Content-Type: application/json

{
    "name": "Semangkamedia",
    "username": "abu.kafa",
    "password": "rahasia",
    "division": "Programmer",
    "position": "Lead Developer",
    "role": "5"
}

###
PUT http://localhost:8000/api/user/2
Content-Type: application/json

{
    "name": "Hijaz Abdullah",
    "username": "jaz1453",
    "password": "rahasia",
    "division": "Management",
    "position": "CEO",
    "role": "4"
}

###
DELETE http://localhost:8000/api/user/3